// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUVqVRglFvVLr9mnASCgZLb4NwpwLHZP4',
    appId: '1:94832024706:web:3121159001e9492fca689b',
    messagingSenderId: '94832024706',
    projectId: 'mentomate-b6383',
    authDomain: 'mentomate-b6383.firebaseapp.com',
    storageBucket: 'mentomate-b6383.appspot.com',
    measurementId: 'G-HCL45XZE7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsgbCOZxHPdU1TG_yZY4pGd_ntHMOPfto',
    appId: '1:94832024706:android:855a0e5067859918ca689b',
    messagingSenderId: '94832024706',
    projectId: 'mentomate-b6383',
    storageBucket: 'mentomate-b6383.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYav_f2CUmuwX175s43hRw2dWaTf0lNKg',
    appId: '1:94832024706:ios:d9494760f947d785ca689b',
    messagingSenderId: '94832024706',
    projectId: 'mentomate-b6383',
    storageBucket: 'mentomate-b6383.appspot.com',
    iosBundleId: 'com.example.madproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYav_f2CUmuwX175s43hRw2dWaTf0lNKg',
    appId: '1:94832024706:ios:d9494760f947d785ca689b',
    messagingSenderId: '94832024706',
    projectId: 'mentomate-b6383',
    storageBucket: 'mentomate-b6383.appspot.com',
    iosBundleId: 'com.example.madproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUVqVRglFvVLr9mnASCgZLb4NwpwLHZP4',
    appId: '1:94832024706:web:b0cc03156e50b552ca689b',
    messagingSenderId: '94832024706',
    projectId: 'mentomate-b6383',
    authDomain: 'mentomate-b6383.firebaseapp.com',
    storageBucket: 'mentomate-b6383.appspot.com',
    measurementId: 'G-33M9VBWP2Z',
  );
}
